// source: proto/event.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.event.ProcessEventRequest', null, global);
goog.exportSymbol('proto.event.ProcessEventResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.event.ProcessEventRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.event.ProcessEventRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.event.ProcessEventRequest.displayName = 'proto.event.ProcessEventRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.event.ProcessEventResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.event.ProcessEventResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.event.ProcessEventResponse.displayName = 'proto.event.ProcessEventResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.event.ProcessEventRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.event.ProcessEventRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.event.ProcessEventRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.event.ProcessEventRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    agregadorid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agregadornombre: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tipoevento: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tenantid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fechaevento: jspb.Message.getFieldWithDefault(msg, 5, ""),
    mensajeid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    usuarioid: jspb.Message.getFieldWithDefault(msg, 7, ""),
    topico: jspb.Message.getFieldWithDefault(msg, 8, ""),
    cuerpoevento: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.event.ProcessEventRequest}
 */
proto.event.ProcessEventRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.event.ProcessEventRequest;
  return proto.event.ProcessEventRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.event.ProcessEventRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.event.ProcessEventRequest}
 */
proto.event.ProcessEventRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgregadorid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgregadornombre(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTipoevento(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFechaevento(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMensajeid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsuarioid(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopico(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCuerpoevento(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.event.ProcessEventRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.event.ProcessEventRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.event.ProcessEventRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.event.ProcessEventRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAgregadorid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAgregadornombre();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTipoevento();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTenantid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFechaevento();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMensajeid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUsuarioid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTopico();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCuerpoevento();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string agregadorId = 1;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getAgregadorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setAgregadorid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string agregadorNombre = 2;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getAgregadornombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setAgregadornombre = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tipoEvento = 3;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getTipoevento = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setTipoevento = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string tenantId = 4;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getTenantid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setTenantid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string fechaEvento = 5;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getFechaevento = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setFechaevento = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string mensajeId = 6;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getMensajeid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setMensajeid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string usuarioId = 7;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getUsuarioid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setUsuarioid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string topico = 8;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getTopico = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setTopico = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string cuerpoEvento = 9;
 * @return {string}
 */
proto.event.ProcessEventRequest.prototype.getCuerpoevento = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventRequest} returns this
 */
proto.event.ProcessEventRequest.prototype.setCuerpoevento = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.event.ProcessEventResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.event.ProcessEventResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.event.ProcessEventResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.event.ProcessEventResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    saved: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.event.ProcessEventResponse}
 */
proto.event.ProcessEventResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.event.ProcessEventResponse;
  return proto.event.ProcessEventResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.event.ProcessEventResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.event.ProcessEventResponse}
 */
proto.event.ProcessEventResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSaved(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.event.ProcessEventResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.event.ProcessEventResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.event.ProcessEventResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.event.ProcessEventResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSaved();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool saved = 1;
 * @return {boolean}
 */
proto.event.ProcessEventResponse.prototype.getSaved = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.event.ProcessEventResponse} returns this
 */
proto.event.ProcessEventResponse.prototype.setSaved = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.event.ProcessEventResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.event.ProcessEventResponse} returns this
 */
proto.event.ProcessEventResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.event);
